Enums multiple statements and more
mypricehealth/pggen pull request #3
Opened 2024-10-30 12:18 UTC by DavidArchibald

Here's a timeline of events:
- Kirk Anchor wanted composite type support for their own purposes and made a fork where they worked on this.
- You made some changes to JSONB etc. (this unfortunately means this'll be included in the diff).
- I added improvements to pggen

The new features are:
- Composite types (thanks to Kirk Anchor), error wrapping, and some other minor fixes
- Lazy registering types on first query.
- Enum improvements like naming conflicts
- Multi statement support. Namely you can now write `SELECT 1; SELECT 2;` in one "query group". This is by far the most complex part of this.

2024-10-30 13:01 UTC, DavidArchibald commented on Makefile
> +	DOCKER_API_VERSION=1.39 go test ./example/acceptance_test.go -update
This is one of kirk anchor's changes, in truth I'm not 100% sure what it's about but it's probably to address some deprecation in Docker?

2024-10-30 13:01 UTC, DavidArchibald commented on example/author/query.sql.go
These are expected changes to the tests.

2024-10-30 13:01 UTC, DavidArchibald commented on generate_test.go
> +	"github.com/mypricehealth/pggen/internal/pgtest"
I believe these imports got shuffled around just by virtue of multiple hands touching this.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/ast/ast.go
> +		PreparedSQL string        // The prepared sql to be executed.
For an input SQL like `SELECT pggen.arg('arg0'), pggen.arg('arg1'); SELECT pgen.arg('arg2'), pggen.arg('arg0');` this is how it'll be parsed out:

`SourceSQL` will be pretty much the same, just a list of the queries so `SELECT pggen.arg('arg0'), pggen.arg('arg1');` as one item and then `SELECT pgen.arg('arg2'), pggen.arg('arg0');`
By comparison `DenseSQL` will look something like `SELECT $1, $2` and then `SELECT $1, $2;`. It also contains an `Args` array which is a list of indexes back to the original query parameter. For example in the second query `$2` actually associates to `arg0` which is at index 0.

Note that `DenseSQL` ignores the fact that `arg0` is reused across multiple queries. This is useful during preparation because for some reason the extended query protocol whines when you have an unbound parameter, even if it's just used in a prior query. This is strange to me because it seems to make it quite difficult to send a query like `SELECT $1` followed by `SELECT $2`.

You can't even batch them up because the protocol doesn't allow multiple. Other protocols like the simple one doesn't allow query parameters at all but there's got to be a way since PGX can execute `SELECT $1; SELECT $2;` just fine. I think it may be a pgx convenience? I decided not to dig any deeper because I didn't want to spend time on something not pivotal. This is a lot of where the complexity crops up so it's still unfortunate.

I might look into it again sometime. Likely on my own time because this is quite interesting to me.

Finally `PreparedSQL` is what's actually executed by the end put into the generated `.go` file. In the examples I've been talking about it looks like `SELECT $1, $2; SELECT $3, $1;`. Intuitively, each 'named' arg maps to one unique numerical index, so even though `arg0` shows up multiple times it gets used as `$1` in both positions.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/declarer.go
> +	}
When dealing with composite types (and arrays of composite types), pgx needs to "register" this type in order to be able to be able to decode it. You can see what goes into the final generated file in the `typeResolverInitDecl` machinery later in this file.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/declarer.go
> +		pgxdecimal.Register(typeMap)
pgxdecimal is always registered. Arguably usage could be detected and only loaded when needed but it's not exactly a huge cost to add.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/declarer.go
> +			typeMap.RegisterType(dt)
This just uses the built in pgx `LoadType` and `RegisterType`, convenient right?

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/gotype/known_types.go
> +	JSON          = MustParseKnownType("encoding/json.RawMessage", pg.JSON)
Some of this is your change. The only reason you're seeing this is because kirk anchor's change is chronologically before this.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/gotype/types.go
> +func makeUnique(labels []string) []string {
I added this to fix conflicting enum names. For example `Value 123` and `Value 456` will be given the same name in Go because numbers are stripped. I considered also going through the effort of avoiding stripping out characters except when absolutely necessary but I didn't worry too much about this.

I don't love just appending the index, i.e. `SomeNameWithConflict_15` and `SomeNameWithConflict_17` or whatever because it's not super stable but I don't actually think people will be referencing the enum variants from pggen that often.

I really just added this so the file would compile. I could've torn it out entirely, I just thought the generation was neat.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/gotype/types.go
> +	}
Courtesy of Kirk Anchor. If the type is something generic like `pgtype.FlatArray[X.Y]` or whatever, this tries to handle it.

I think there's arguably a bug? Since it expects it to be the form of `pgtype.FlatArray[X.Y]` and it gets just the `Y` but it doesn't account for the form `pgtype.FlatArray[X]`; it'd return `X]` in that case. If you agree it's a bug I'll go ahead and fix it.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/query.gotemplate
> +    }
This is the final part to the `registerTypes` tweaks I added on top of what Kirk Anchor did. They initially expected you to add `registerTypes` as a part of creating the conn but it didn't really work very well with our `pool` API. I did end up having to make tweaks to expose `LoadType` and such but this way had other benefits too.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/query.gotemplate
> +{{ if false }}
This is another Kirk Anchor change. The stuff below this in the template is how registering types _used_ to work. We can probably just delete it entirely if wanted.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/templated_file.go
> +			return toZeroValue(goType), nil
This is a fix from me to get a zero value for enums properly.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/codegen/golang/templated_file.go
> -			sb.WriteString("q.types.")
This is removing some of the old register types stuff.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/parser/parser.go
> +	}
The diff is bad here, I just refactored out `handleCommentGroup` for reasons I'll elaborate on later.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/parser/parser.go
> +	var endPos gotok.Pos
This is the parsing code related directly to multiline queries. There's a lot more state to track now but it's all relatively straightforward purposes from previous comments.

I've written so many comments on this PR because I don't believe `denseSQL` is a self-documenting concept etc.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/parser/parser.go
> +			arg.hi -= int(queryStartPos)
this is just to account for the fact that `pos` isn't the start of the query anymore (because there may be multiple)

2024-10-30 13:01 UTC, DavidArchibald commented on internal/parser/parser.go
> +			p.handleCommentGroup(prev)
This is why I refactored out `p.handleCommentGroup`. The way `p.tok` works is that it's a 1 token lookahead. So directly above I lookahead to see if there's a `newQueryGroup`. The behaviour of `p.next()` is to read past all comments because the assumption was that parsing would stop after a query finished.

However, now I don't want to read past them until I've written the current SQL because if I did, I'd be able to miss the `LineComment` that corresponds to the start of a new query group. I use `p.next0()` to avoid reading comment groups but to _also_ avoid the comment from being included as the start of the next query I run `p.handleCommentGroup(prev)` to skip over it.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/parser/parser_test.go
> +	return cmpopts.IgnoreFields(ast.SourceQuery{}, "Start", "EndPos")
This is a cool API, I kind of wish we had it in our repo.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/pginfer/explain.go
> +	row := inf.conn.QueryRow(ctx, explainQuery, createParamArgs(len(lastSQL.Args))...)
Now that multiple statements can be executed, `EXPLAIN` _would_ break as it only supports 1 statement. Fortunately only the last statement has to be explained but since the previous statements can have side effects (e.g. `insert_with_id` adding a `xyz_id` table) it still needs to be run, albeit in a transaction.

I do sort of want to figure out if there's a better way as it could be reasonable to error when only given `NULL` for query parameters. It could also be reasonable to start a transaction yourself, but this would fail as it's currently within a transaction during analyzing (so that it can be rolled back). Still those aren't questions that have to be answered today.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/pginfer/pginfer.go
> +}
Similarly during preparing the queries (to get the types of the query parameters) they must be prepared _and_ executed in a transaction.

I should probably reuse this transaction to do the `EXPLAIN` but I wrote this to see if it'd work not to see the best way to do it.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/pginfer/pginfer.go
> +		}
This is a bit more obtuse to execute than you'd normally go about it but its fundamentally just executing the query with null parameters.

2024-10-30 13:01 UTC, DavidArchibald commented on internal/pginfer/pginfer.go
> +	for i, statement := range statements {
Everything is complicated by having multiple statements but don't let the messy diff in this function fool you, this is ultimately mostly a refactor to add a for loop and an extra parameter index remapping. A lot of the logic already existed.

2024-10-30 14:11 UTC, DavidArchibald commented on internal/parser/parser.go
> +			p.handleCommentGroup(prev)
Newly handled in a different way, may ignore.

2024-11-04 20:51 UTC, robarchibald requested changes
Looks good. Just a couple of questions and clarifications to consider.

2024-11-04 20:51 UTC, robarchibald commented on internal/codegen/golang/gotype/types.go
> +			seen[label] = false
This reads the opposite of what I would expect here. You're setting `seen[label]` to `false` when the label has been seen before. Confused

2024-11-04 20:51 UTC, robarchibald commented on internal/ast/ast.go
> +		DenseSQL    []DenseSQL    // a list of sql queries with args replaced by dense placeholders with a mapping to the real placeholders. Useful for `Prepare`.
DenseSQL doesn't really mean anything to me. Since we restart each statement at $1, how about instead we call this `ReorderedArgsSQL` instead?

2024-11-04 21:27 UTC, DavidArchibald commented on internal/ast/ast.go
> +		DenseSQL    []DenseSQL    // a list of sql queries with args replaced by dense placeholders with a mapping to the real placeholders. Useful for `Prepare`.
Reordered is a much more vague word in my mind. Reordered how? Contiguous or Dense both imply something about the shape; dense in general but especially in computer science means minimal to no gaps.

The closest analogy here is "dense array" is one in which there's no big jumps. A reordered array in my mind is much more random.

I'd be happy with `ContiguousArgsSQL`.

2024-11-04 21:28 UTC, DavidArchibald commented on internal/codegen/golang/gotype/types.go
> +			seen[label] = false
That's true, I'll go for `unique` then?

2024-11-05 17:49 UTC, robarchibald commented on internal/ast/ast.go
> +		DenseSQL    []DenseSQL    // a list of sql queries with args replaced by dense placeholders with a mapping to the real placeholders. Useful for `Prepare`.
ContiguousArgsSQL sounds fine

2024-11-05 17:49 UTC, robarchibald commented on internal/codegen/golang/gotype/types.go
> +			seen[label] = false
Sounds good

2024-11-05 19:49 UTC, merged